# Generated by Django 3.2.3 on 2021-05-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='place_id',
        ),
        migrations.AddField(
            model_name='place',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
