# Generated by Django 3.2.3 on 2021-05-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0002_auto_20210529_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='call',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='day_break',
        ),
        migrations.RemoveField(
            model_name='place',
            name='division',
        ),
        migrations.RemoveField(
            model_name='place',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='place',
            name='explain',
        ),
        migrations.RemoveField(
            model_name='place',
            name='locate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='place',
            name='time',
        ),
    ]
