# Generated by Django 3.2.3 on 2021-05-27 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0002_auto_20210527_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='choice_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='greentable.choice'),
            preserve_default=False,
        ),
    ]
