# Generated by Django 3.2.3 on 2021-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0003_auto_20210529_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='call',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='day_break',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='etc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='explain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='locate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='menu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
