# Generated by Django 3.2.3 on 2021-05-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0004_auto_20210527_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='division',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
