# Generated by Django 3.2.3 on 2021-05-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0004_auto_20210529_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
