# Generated by Django 3.2.3 on 2021-06-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0005_alter_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('contets', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=100)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greentable.place')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greentable.question')),
            ],
        ),
    ]
