# Generated by Django 3.2.3 on 2021-05-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0006_auto_20210527_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='day_break',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='etc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='menu',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
