# Generated by Django 3.2.3 on 2021-06-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0007_choice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='place',
        ),
    ]
