# Generated by Django 3.2.3 on 2021-05-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0008_place_choice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='call',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='day_break',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='division',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='etc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='explain',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='locate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='menu',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
