# Generated by Django 3.2.3 on 2021-06-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0008_remove_choice_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='contets',
            new_name='content',
        ),
    ]
