# Generated by Django 3.2.3 on 2021-05-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0009_auto_20210527_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='choice_id',
        ),
    ]
