# Generated by Django 3.2.3 on 2021-05-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0010_remove_place_choice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='place_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='greentable.place'),
            preserve_default=False,
        ),
    ]
