# Generated by Django 3.2.3 on 2021-05-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentable', '0011_choice_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='place_id',
        ),
    ]
